workflows:
  android_debug_apk_diag:
    name: Android Debug APK (deep diagnostics)
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches
        - $FCI_BUILD_DIR/build
    scripts:
      - echo "=== Versions ==="
      - flutter --version
      - java -version || true

      - echo "=== Ensure platform folders ==="
      - |
        if [ ! -d "android" ]; then
          echo "android/ missing -> running 'flutter create .'"
          flutter create .
        fi

      - echo "=== Patch android/settings.gradle.kts (repos) ==="
      - |
        SETTINGS="android/settings.gradle.kts"
        if [ -f "$SETTINGS" ]; then
          cat > "$SETTINGS" <<'KTS'
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "android"
include(":app")
KTS
        fi
        echo "----- android/settings.gradle.kts -----"
        cat android/settings.gradle.kts || true

      - echo "=== Prepare ==="
      - flutter clean
      - flutter pub get
      - flutter analyze || true

      - echo "=== Ensure gradle.properties ==="
      - |
        GP="android/gradle.properties"
        touch "$GP"
        grep -q '^android.useAndroidX=' "$GP" || echo 'android.useAndroidX=true' >> "$GP"
        grep -q '^android.enableJetifier=' "$GP" || echo 'android.enableJetifier=true' >> "$GP"
        grep -q '^org.gradle.jvmargs=' "$GP" || echo 'org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g' >> "$GP"
        echo "----- android/gradle.properties -----"
        cat "$GP" || true

      - echo "=== Show app build.gradle.kts ==="
      - cat android/app/build.gradle.kts || true

      - echo "=== Build with Gradle directly (stacktrace/info) ==="
      - |
        set -o pipefail
        cd android
        ./gradlew --version || true
        ./gradlew assembleDebug --stacktrace --info 2>&1 | tee ../gradle-debug.log
        cd ..
        # Try Flutter build as well to emit its verbose log (doesn't fail the step)
        flutter build apk --debug -v 2>&1 | tee build-verbose.log || true

    artifacts:
      - gradle-debug.log
      - build-verbose.log
      - build/app/outputs/flutter-apk/app-debug.apk
