workflows:
  android_debug_apk_diag:
    name: Android Debug APK (diagnostic, no chmod)
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches
        - $FCI_BUILD_DIR/build
    scripts:
      - echo "=== Versions ==="
      - flutter --version
      - java -version || true
      - echo "=== Ensure platform folders ==="
      - |
        if [ ! -d "android" ]; then
          echo "android/ missing -> running 'flutter create .'"
          flutter create .
        fi
        echo "=== Listing android/ ==="
        ls -la android || true
      - echo "=== Prepare ==="
      - flutter clean
      - flutter pub get
      - flutter analyze || true
      - echo "=== Patch Gradle (Kotlin DSL) for CI stability ==="
      - |
        FILE="android/app/build.gradle.kts"
        if [ -f "$FILE" ]; then
          # compileSdk 34
          sed -i.bak 's/compileSdk\s*=\s*[^0-9]*/compileSdk = 34/' "$FILE" || true
          # minSdk 23
          sed -i.bak 's/minSdk\s*=\s*[0-9]\+/minSdk = 23/' "$FILE" || true
          # targetSdk 34
          sed -i.bak 's/targetSdk\s*=\s*[0-9]\+/targetSdk = 34/' "$FILE" || true
          # Java 17
          sed -i.bak 's/JavaVersion\.VERSION_[0-9]\+/JavaVersion.VERSION_17/g' "$FILE" || true
          sed -i.bak 's/jvmTarget\s*=\s*"[0-9]\+"/jvmTarget = "17"/' "$FILE" || true
        fi
      - echo "=== Gradle properties (AndroidX + memory) ==="
      - |
        GP="android/gradle.properties"
        touch "$GP"
        grep -q '^android.useAndroidX=' "$GP" || echo 'android.useAndroidX=true' >> "$GP"
        grep -q '^android.enableJetifier=' "$GP" || echo 'android.enableJetifier=true' >> "$GP"
        grep -q '^org.gradle.jvmargs=' "$GP" || echo 'org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g' >> "$GP"
      - echo "=== Build (verbose) ==="
      - |
        set -o pipefail
        flutter build apk --debug -v 2>&1 | tee build-verbose.log
    artifacts:
      - build-verbose.log
      - build/app/outputs/flutter-apk/app-debug.apk

  android_release:
    name: Android Release (APK + AAB, no chmod)
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/.gradle/caches
        - $FCI_BUILD_DIR/build
    scripts:
      - |
        if [ ! -d "android" ]; then
          echo "android/ missing -> running 'flutter create .'"
          flutter create .
        fi
      - flutter clean
      - flutter pub get
      - |
        FILE="android/app/build.gradle.kts"
        if [ -f "$FILE" ]; then
          sed -i.bak 's/compileSdk\s*=\s*[^0-9]*/compileSdk = 34/' "$FILE" || true
          sed -i.bak 's/minSdk\s*=\s*[0-9]\+/minSdk = 23/' "$FILE" || true
          sed -i.bak 's/targetSdk\s*=\s*[0-9]\+/targetSdk = 34/' "$FILE" || true
          sed -i.bak 's/JavaVersion\.VERSION_[0-9]\+/JavaVersion.VERSION_17/g' "$FILE" || true
          sed -i.bak 's/jvmTarget\s*=\s*"[0-9]\+"/jvmTarget = "17"/' "$FILE" || true
        fi
      - flutter build apk --release
      - flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
